### ISSUE TITLE
Friendly reminder: Not ready yet

### ISSUE THREAD

**Issue by GeorgeS2019** [sps014/BlazorML5#13] opened 2022-06-18 10:50 UTC
@sps014 

Since this repository has gone through significant changes after merging the [v2 branch](https://github.com/sps014/BlazorML5/tree/v2). 

I have tested the latest master branch, there is no machine learning, and the [Navigation links are blank. ](https://github.com/sps014/BlazorML5/issues/11)

I could not find anywhere with the necessary ML5 calling script which was last seen in the [.NET5 branch](https://github.com/sps014/BlazorML5/tree/net5)

 [<script src="https://unpkg.com/ml5@latest/dist/ml5.min.js"></script>](https://github.com/sps014/BlazorML5/blob/c4e8f1fc8f9eca4f5869f21cba074c97921661f4/DemoApplication/wwwroot/index.html#L19)

It would be friendly to the community to ask notify that this is WIP. **Many regression warnings**!

**Comment by sps014** [comment] 2022-06-18 10:55
Honestly I couldn't motivate myself to redesign ui, I focused on lib itself, it is in working condition and nuget packages are up to date. I accepts PR of all kind feel free to drop one thanks.

**Comment by GeorgeS2019** [comment] 2022-06-18 11:01
@sps014 

I keep coming back after a recent survey of the status of Javascript interopt done in the official Blazor and Jint. 

I still think it is VERY INTERESTING what you have started. 
I am still trying to figure out your approaches, strength, and weakness.

It takes a community to follow your idea to test iteratively until many believe there is something worth recommending to the official blazor approach.

I have already share your repository to the aspdotnet gitter site. 

I have seen your other repositories. 

There are mostly proving to you that you are capable. 

But Blazor binding is very Unique in my view

Obviously that Blazor JS Interope continues to improve. 

Perhaps you would like to share **you have different ideas** with respect to the official approach.

**Comment by GeorgeS2019** [comment] 2022-06-18 11:04
@sps014 

There are many excellent .NET github projects. However, there are still many unmet .NET community needs.

e.g.  Keeping machine learning within .NET without needing going to python.

TorchSharp is such an attempt. 

TorchSharp is now mainstream and many are starting to contribute with regular questions and discussions to achieve what many think is hard to achieve.

**Comment by sps014** [comment] 2022-06-18 14:31
Duplicate of https://github.com/sps014/BlazorML5/issues/14

**Closed as completed by sps014** 2022-06-18 14:31 UTC
