### ISSUE TITLE
NavMenu.razor is blank

### ISSUE THREAD

**Issue by GeorgeS2019** [sps014/BlazorML5#11] opened 2022-06-17 23:59 UTC
https://github.com/sps014/BlazorML5/blob/master/SampleApp/Shared/NavMenu.razor

**Comment by GeorgeS2019** [comment] 2022-06-18 00:01
possible content

https://github.com/sps014/BlazorML5/blob/development/DemoApplication/Shared/NavMenu.razor

**Comment by GeorgeS2019** [comment] 2022-06-18 10:52
The provided NavMenu does not reflect the live demo

![image](https://user-images.githubusercontent.com/49812372/174434479-18542741-7526-426e-b498-0ede4ddb85d8.png)

**Comment by sps014** [comment] 2022-06-18 14:33
I will add this weekend.
Closing as of now.
Duplicate of https://github.com/sps014/BlazorML5/issues/14

**Closed as completed by sps014** 2022-06-18 14:33 UTC
